name: live_location_example
description: "Demonstrates how to use the live_location plugin."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_live_location:
    path: ../
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
